media:
  input: public
  output: /
content:
  - name: lessons
    label: Lessons
    type: collection
    path: src/content/lessons
    view:
      fields: [title, draft, description, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: draft, label: Draft, type: boolean }
      - { name: description, label: Description, type: string }
  - name: topics
    label: Topics
    type: collection
    path: src/content/topics
    view:
      fields: [title, draft, description, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
